--- 
  - debug: msg="RTWS_DOMAIN={{ RTWS_DOMAIN }}"
    
  - alternatives: name=hadoop-conf path=install link=/etc/hadoop/conf path={{ deb_install_prefix }}/cluster
  
  - copy: src=datanode-watchdog.sh dest=/usr/local/bin/datanode-watchdog.sh owner=root group=root mode=0555

  - file: path=/var/run/hadoop-hdfs state=directory owner=root group=root mode=0755

  - copy: hadoop-config-v2-jmx-agent.jar /etc/hadoop/conf/jmx-agent.jar owner=root group=root mode=0444

  - shell: perl -i -pe 's:HADOOP_MAPRED_HOME=/usr/lib/hadoop-mapreduce:HADOOP_MAPRED_HOME=/usr/lib/hadoop-0.20-mapreduce:g' /etc/default/hadoop

  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:{{ RTWS_DOMAIN }}:g' /etc/hadoop/conf/core-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:{{ RTWS_DOMAIN }}:g' /etc/hadoop/conf/hdfs-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:{{ RTWS_DOMAIN }}:g' /etc/hadoop/conf/mapred-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_ZOOKEEPER_QUORUM_SERVERS\}:{{ RTWS_ZOOKEEPER_QUORUM_SERVERS }}:g' /etc/hbase/conf/hbase-site.xml