---
  - name: Install Configs
    command: echo "go boy for {{ RTWS_DOMAIN }}"
 
  - shell: perl -i -pe 's:<!-- REPLACE_SLAVE_HOST_NAME -->:<property><name>slave.host.name</name><value>$ENV{R_RTWS_FQDN}</value></property>:g' /etc/hadoop/conf/mapred-site.xml

  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/core-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/hdfs-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/mapred-site.xml
  
  - shell: perl -i -pe 's:\$\{RTWS_ZOOKEEPER_QUORUM_SERVERS\}:$ENV{R_ZKSERVERS}:g' /etc/hbase/conf/hbase-site.xml